"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 3 — per-trace budget tracker.
//
// Two ceilings, both opt-in:
//   LLM_BUDGET_TOKENS_PER_TRACE  — absolute tokens (prompt + completion)
//   LLM_BUDGET_USD_PER_TRACE     — fractional USD (cost class lookup table
//                                   gives a pessimistic per-1k-tokens price)
//
// When neither is set, the tracker is permissive — it still records spend
// for observability but never throws.
Object.defineProperty(exports, "__esModule", { value: true });
exports.BudgetExceededError = void 0;
exports.newBudget = newBudget;
exports.budgetEnforced = budgetEnforced;
exports.budgetLimits = budgetLimits;
const metrics_1 = require("../metrics");
/** Pessimistic per-1k-tokens USD floor by cost class. Used when models
 * don't carry a cost-per-token annotation. Numbers are deliberately on the
 * high side so the gauge never under-bills.
 */
const COST_FLOOR = {
    tiny: 0.0001,
    small: 0.0010,
    medium: 0.0100,
    large: 0.0300,
};
class BudgetExceededError extends Error {
    trace_id;
    kind;
    limit;
    observed;
    code = "BUDGET_EXCEEDED";
    constructor(message, trace_id, kind, limit, observed) {
        super(message);
        this.trace_id = trace_id;
        this.kind = kind;
        this.limit = limit;
        this.observed = observed;
        this.name = "BudgetExceededError";
    }
}
exports.BudgetExceededError = BudgetExceededError;
function readLimit(envName) {
    const raw = process.env[envName];
    if (!raw)
        return null;
    const v = Number(raw);
    if (!Number.isFinite(v) || v <= 0)
        return null;
    return v;
}
const TOKEN_LIMIT = readLimit("LLM_BUDGET_TOKENS_PER_TRACE");
const USD_LIMIT = readLimit("LLM_BUDGET_USD_PER_TRACE");
class StandardBudget {
    trace_id;
    _tokens = 0;
    _usd = 0;
    constructor(trace_id) { this.trace_id = trace_id; }
    get tokens() { return this._tokens; }
    get usd() { return this._usd; }
    projectedUsd(addTokens, costClass) {
        const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
        return this._usd + (addTokens / 1000) * rate;
    }
    assertCanSpend(tokens, costClass) {
        if (TOKEN_LIMIT !== null && this._tokens + tokens > TOKEN_LIMIT) {
            (0, metrics_1.counter)("cognition.budget_exceeded", { kind: "tokens" });
            throw new BudgetExceededError(`Trace ${this.trace_id} would exceed token budget (${this._tokens + tokens} > ${TOKEN_LIMIT})`, this.trace_id, "tokens", TOKEN_LIMIT, this._tokens + tokens);
        }
        if (USD_LIMIT !== null) {
            const projected = this.projectedUsd(tokens, costClass);
            if (projected > USD_LIMIT) {
                (0, metrics_1.counter)("cognition.budget_exceeded", { kind: "usd" });
                throw new BudgetExceededError(`Trace ${this.trace_id} would exceed USD budget ($${projected.toFixed(4)} > $${USD_LIMIT})`, this.trace_id, "usd", USD_LIMIT, projected);
            }
        }
    }
    charge(tokens, costClass) {
        if (tokens <= 0)
            return;
        this._tokens += tokens;
        const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
        this._usd += (tokens / 1000) * rate;
        (0, metrics_1.counter)("cognition.tokens_charged", { cost_class: costClass });
        (0, metrics_1.gauge)("cognition.trace_tokens", this._tokens, { trace_id: this.trace_id });
        (0, metrics_1.gauge)("cognition.trace_usd", this._usd, { trace_id: this.trace_id });
    }
    refund(tokens, costClass) {
        if (tokens <= 0)
            return;
        this._tokens = Math.max(0, this._tokens - tokens);
        const rate = COST_FLOOR[costClass] ?? COST_FLOOR.small;
        this._usd = Math.max(0, this._usd - (tokens / 1000) * rate);
        (0, metrics_1.counter)("cognition.tokens_refunded", { cost_class: costClass });
    }
}
function newBudget(trace_id) {
    return new StandardBudget(trace_id);
}
/** True if either ceiling is configured. Useful for callsite branching. */
function budgetEnforced() {
    return TOKEN_LIMIT !== null || USD_LIMIT !== null;
}
/** Internal: expose the (immutable) limits for tests / observability. */
function budgetLimits() {
    return { tokens: TOKEN_LIMIT, usd: USD_LIMIT };
}
