"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 3 — prompt cache.
//
// Two storage modes, switched by env var LLM_CACHE_MODE:
//   memory  — in-process Map, useful for tests and single-instance dev (default)
//   pg      — Postgres-backed, durable across restarts and HA workers
//
// Both modes share the same get/put/deriveKey API. The cognition runtime
// always asks the cache, never the storage backend directly.
Object.defineProperty(exports, "__esModule", { value: true });
exports.cache = void 0;
exports.deriveKey = deriveKey;
exports.__resetMemoryCache = __resetMemoryCache;
const crypto_1 = require("crypto");
const metrics_1 = require("../metrics");
const logger_1 = require("../logger");
/**
 * Canonical-JSON stringify: keys are sorted at every level so two
 * objects with the same content produce identical strings regardless
 * of declaration order. Used as the basis for the cache key.
 */
function canonical(value) {
    if (value === null || value === undefined)
        return JSON.stringify(value ?? null);
    if (typeof value !== "object")
        return JSON.stringify(value);
    if (Array.isArray(value))
        return "[" + value.map(canonical).join(",") + "]";
    const obj = value;
    const keys = Object.keys(obj).sort();
    return "{" + keys.map(k => JSON.stringify(k) + ":" + canonical(obj[k])).join(",") + "}";
}
/**
 * Derive a 64-char hex key. The runtime passes the rendered template
 * as `template_hash` so prompt rewordings invalidate the cache.
 */
function deriveKey(args) {
    const composite = [
        args.prompt_name,
        args.model_id,
        args.template_hash,
        args.output_type,
        canonical(args.input),
    ].join("|");
    return (0, crypto_1.createHash)("sha256").update(composite).digest("hex");
}
class MemoryCache {
    store = new Map();
    async get(key) {
        const e = this.store.get(key);
        if (!e)
            return null;
        if (e.expires_at < Date.now()) {
            this.store.delete(key);
            return null;
        }
        return e;
    }
    async put(key, _prompt, _model, value, ttl_ms, usage) {
        const now = Date.now();
        this.store.set(key, {
            value,
            prompt_tokens: usage.prompt_tokens ?? null,
            completion_tokens: usage.completion_tokens ?? null,
            cost_usd: usage.cost_usd ?? null,
            cached_at: now,
            expires_at: now + ttl_ms,
        });
    }
}
class PgCache {
    async get(key) {
        // Lazy import — keeps tests that don't exercise PG mode free of pg dependency.
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const { query } = require("../db");
        const rows = await query(`UPDATE prompt_cache SET hits = hits + 1, last_hit_at = NOW()
        WHERE cache_key = $1 AND expires_at > NOW() RETURNING *`, [key]);
        if (rows.length === 0)
            return null;
        const r = rows[0];
        return {
            value: r.output_value,
            prompt_tokens: r.prompt_tokens,
            completion_tokens: r.completion_tokens,
            cost_usd: r.cost_usd === null ? null : Number(r.cost_usd),
            cached_at: new Date(r.created_at).getTime(),
            expires_at: new Date(r.expires_at).getTime(),
        };
    }
    async put(key, prompt_name, model_id, value, ttl_ms, usage) {
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const { query } = require("../db");
        await query(`INSERT INTO prompt_cache (cache_key, prompt_name, model_id, output_value, prompt_tokens, completion_tokens, cost_usd, expires_at)
        VALUES ($1, $2, $3, $4, $5, $6, $7, NOW() + ($8 || ' milliseconds')::interval)
        ON CONFLICT (cache_key) DO UPDATE SET
          output_value = EXCLUDED.output_value,
          expires_at = EXCLUDED.expires_at,
          last_hit_at = NULL,
          hits = 0`, [key, prompt_name, model_id, JSON.stringify(value), usage.prompt_tokens ?? null, usage.completion_tokens ?? null, usage.cost_usd ?? null, ttl_ms]);
    }
}
function chooseBackend() {
    const mode = process.env.LLM_CACHE_MODE || "memory";
    if (mode === "pg")
        return new PgCache();
    if (mode !== "memory") {
        logger_1.logger.warn("prompt_cache_unknown_mode", { event: "cache", status: "rejected", metadata: { mode } });
    }
    return new MemoryCache();
}
const __backend = chooseBackend();
/** Public cache. Counters are emitted on every get/put for hit-rate observability. */
exports.cache = {
    async get(key) {
        const e = await __backend.get(key);
        (0, metrics_1.counter)(e ? "cognition.cache_hit" : "cognition.cache_miss");
        return e;
    },
    async put(key, prompt_name, model_id, value, ttl_ms, usage) {
        await __backend.put(key, prompt_name, model_id, value, ttl_ms, usage);
        (0, metrics_1.counter)("cognition.cache_put", { prompt: prompt_name });
    },
};
/** For tests: clear the in-memory cache. No-op against PG mode. */
function __resetMemoryCache() {
    if (__backend instanceof MemoryCache) {
        // @ts-expect-error — internal field for tests
        __backend.store.clear();
    }
}
