"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — public entry.
//
// Application code imports `getCognition` to get a CognitionCtx wired
// to all declared models, prompts, routers, and primitives.
Object.defineProperty(exports, "__esModule", { value: true });
exports.getModel = exports.listModelNames = exports.getRouter = exports.ROUTERS = exports.findSummarizer = exports.getPrompt = exports.PROMPTS = void 0;
exports.newTraceId = newTraceId;
exports.callPrompt = callPrompt;
const providers_1 = require("../providers");
Object.defineProperty(exports, "listModelNames", { enumerable: true, get: function () { return providers_1.listModelNames; } });
Object.defineProperty(exports, "getModel", { enumerable: true, get: function () { return providers_1.getModel; } });
const prompts_1 = require("./prompts");
Object.defineProperty(exports, "PROMPTS", { enumerable: true, get: function () { return prompts_1.PROMPTS; } });
Object.defineProperty(exports, "getPrompt", { enumerable: true, get: function () { return prompts_1.getPrompt; } });
Object.defineProperty(exports, "findSummarizer", { enumerable: true, get: function () { return prompts_1.findSummarizer; } });
const router_1 = require("./router");
Object.defineProperty(exports, "ROUTERS", { enumerable: true, get: function () { return router_1.ROUTERS; } });
Object.defineProperty(exports, "getRouter", { enumerable: true, get: function () { return router_1.getRouter; } });
const crypto_1 = require("crypto");
function newTraceId() { return (0, crypto_1.randomUUID)(); }
async function callPrompt(name, input) {
    const fn = (0, prompts_1.getPrompt)(name);
    return fn(input, { trace_id: newTraceId() });
}
