// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — public entry.
//
// Application code imports `getCognition` to get a CognitionCtx wired
// to all declared models, prompts, routers, and primitives.

import { logger } from "../logger";
import { counter } from "../metrics";
import { listModelNames, getModel } from "../providers";
import { PROMPTS, getPrompt, findSummarizer } from "./prompts";
import { ROUTERS, getRouter } from "./router";

import { randomUUID } from "crypto";

export function newTraceId(): string { return randomUUID(); }

export { PROMPTS, getPrompt, findSummarizer };
export { ROUTERS, getRouter };
export { listModelNames, getModel };

export async function callPrompt(name: string, input: Record<string, unknown>): Promise<unknown> {
  const fn = getPrompt(name);
  return fn(input, { trace_id: newTraceId() });
}
