"use strict";
// @ts-nocheck
// Generated by MarrowScript compiler. DO NOT EDIT.
// Bounded Agent Loops (Phase 26) — iterative refinement runtime.
//
// Patterns: generate-validate, generate-critique-revise, decompose-execute-aggregate
// All loops are BOUNDED — max_iterations is enforced at compile time.
Object.defineProperty(exports, "__esModule", { value: true });
exports.runLoop = runLoop;
exports.generateUntilValid = generateUntilValid;
exports.generateCritiqueRevise = generateCritiqueRevise;
const traces_1 = require("./traces");
const metrics_1 = require("../metrics");
const logger_1 = require("../logger");
/**
 * Run a bounded refinement loop.
 *
 * Executes `step()` up to `max_iterations` times. After each step,
 * calls `validate()`. If valid, returns immediately. If not, optionally
 * calls `critique()` to generate feedback for the next iteration.
 *
 * Always terminates. Never recurses. Fully traced.
 */
async function runLoop(config) {
    const startMs = Date.now();
    const state = { current: null, feedback: null, history: [] };
    const iterationHistory = [];
    let bestOutput = null;
    let bestIteration = 0;
    let bestValid = false;
    for (let i = 0; i < config.max_iterations; i++) {
        const iterStart = Date.now();
        // Execute step
        let output;
        try {
            output = await config.step(state, i);
        }
        catch (e) {
            logger_1.logger.error("loop.step_error", { loop: config.name, iteration: i, error: e.message });
            iterationHistory.push({ iteration: i, valid: false, duration_ms: Date.now() - iterStart, feedback: e.message });
            continue;
        }
        // Validate
        let valid;
        try {
            valid = await config.validate(output);
        }
        catch {
            valid = false;
        }
        // Track best
        if (valid || !bestOutput) {
            bestOutput = output;
            bestIteration = i;
            bestValid = valid;
        }
        // Generate feedback if needed
        let feedback = null;
        if (!valid && config.critique) {
            try {
                feedback = await config.critique(output, i);
            }
            catch {
                feedback = "Validation failed, please try again.";
            }
        }
        // Update state
        state.current = output;
        state.feedback = feedback;
        state.history.push({ output, valid, feedback });
        const iterMs = Date.now() - iterStart;
        iterationHistory.push({ iteration: i, valid, duration_ms: iterMs, feedback });
        // Trace
        (0, metrics_1.counter)("cognition.loop.iteration", { loop: config.name, iteration: String(i), valid: String(valid) });
        (0, metrics_1.histogram)("cognition.loop.iteration_ms", iterMs, { loop: config.name });
        // Short-circuit on success
        if (valid) {
            logger_1.logger.info("loop.success", { loop: config.name, iterations: i + 1, total_ms: Date.now() - startMs });
            break;
        }
    }
    const totalMs = Date.now() - startMs;
    // Write summary span
    await (0, traces_1.writeSpan)({
        trace_id: config.trace_id,
        kind: "loop",
        name: config.name,
        status: bestValid ? "ok" : "exhausted",
        duration_ms: totalMs,
        metadata: {
            iterations: iterationHistory.length,
            max_iterations: config.max_iterations,
            best_iteration: bestIteration,
            valid: bestValid,
        },
    });
    if (!bestValid) {
        (0, metrics_1.counter)("cognition.loop.exhausted", { loop: config.name });
        logger_1.logger.warn("loop.exhausted", { loop: config.name, iterations: iterationHistory.length, total_ms: totalMs });
    }
    return {
        output: bestOutput,
        valid: bestValid,
        iterations: iterationHistory.length,
        best_iteration: bestIteration,
        total_ms: totalMs,
        history: iterationHistory,
    };
}
/**
 * Simple generate-until-valid loop.
 * Calls `generate()` repeatedly until `validate()` passes.
 */
async function generateUntilValid(name, generate, validate, options = {}) {
    return runLoop({
        name,
        max_iterations: options.max_iterations || 3,
        trace_id: options.trace_id || "loop-" + Date.now(),
        step: (state, i) => generate(i, state.feedback),
        validate,
        critique: options.critique,
    });
}
/**
 * Generate → Critique → Revise loop.
 * First iteration generates from scratch. Subsequent iterations revise based on feedback.
 */
async function generateCritiqueRevise(name, generate, critique, revise, validate, spec, options = {}) {
    return runLoop({
        name,
        max_iterations: options.max_iterations || 3,
        trace_id: options.trace_id || "loop-" + Date.now(),
        step: async (state, i) => {
            if (i === 0 || !state.current)
                return generate(spec);
            return revise(state.current, state.feedback || "Please improve.");
        },
        validate,
        critique,
    });
}
