// @ts-nocheck
// Generated by MarrowScript compiler. DO NOT EDIT.
// Bounded Agent Loops (Phase 26) — iterative refinement runtime.
//
// Patterns: generate-validate, generate-critique-revise, decompose-execute-aggregate
// All loops are BOUNDED — max_iterations is enforced at compile time.

import { writeSpan } from "./traces";
import { counter, histogram } from "../metrics";
import { logger } from "../logger";

export interface LoopConfig<T> {
  /** Human-readable name for tracing */
  name: string;
  /** Maximum number of iterations before returning best-so-far */
  max_iterations: number;
  /** The step function: takes current state, returns next state */
  step: (state: LoopState<T>, iteration: number) => Promise<T>;
  /** Validation: returns true if the output is acceptable */
  validate: (output: T) => Promise<boolean> | boolean;
  /** Optional: generate feedback for the next iteration */
  critique?: (output: T, iteration: number) => Promise<string>;
  /** Trace ID for the parent span */
  trace_id: string;
}

export interface LoopState<T> {
  /** Current best output */
  current: T | null;
  /** Feedback from previous iteration (if critique is provided) */
  feedback: string | null;
  /** History of all previous outputs */
  history: { output: T; valid: boolean; feedback: string | null }[];
}

export interface LoopResult<T> {
  /** The final output (best result) */
  output: T;
  /** Did validation pass? */
  valid: boolean;
  /** How many iterations ran */
  iterations: number;
  /** Which iteration produced the returned output */
  best_iteration: number;
  /** Total duration across all iterations */
  total_ms: number;
  /** Per-iteration details */
  history: { iteration: number; valid: boolean; duration_ms: number; feedback: string | null }[];
}

/**
 * Run a bounded refinement loop.
 *
 * Executes `step()` up to `max_iterations` times. After each step,
 * calls `validate()`. If valid, returns immediately. If not, optionally
 * calls `critique()` to generate feedback for the next iteration.
 *
 * Always terminates. Never recurses. Fully traced.
 */
export async function runLoop<T>(config: LoopConfig<T>): Promise<LoopResult<T>> {
  const startMs = Date.now();
  const state: LoopState<T> = { current: null, feedback: null, history: [] };
  const iterationHistory: LoopResult<T>["history"] = [];
  let bestOutput: T | null = null;
  let bestIteration = 0;
  let bestValid = false;

  for (let i = 0; i < config.max_iterations; i++) {
    const iterStart = Date.now();

    // Execute step
    let output: T;
    try {
      output = await config.step(state, i);
    } catch (e: any) {
      logger.error("loop.step_error", { loop: config.name, iteration: i, error: e.message });
      iterationHistory.push({ iteration: i, valid: false, duration_ms: Date.now() - iterStart, feedback: e.message });
      continue;
    }

    // Validate
    let valid: boolean;
    try {
      valid = await config.validate(output);
    } catch {
      valid = false;
    }

    // Track best
    if (valid || !bestOutput) {
      bestOutput = output;
      bestIteration = i;
      bestValid = valid;
    }

    // Generate feedback if needed
    let feedback: string | null = null;
    if (!valid && config.critique) {
      try {
        feedback = await config.critique(output, i);
      } catch { feedback = "Validation failed, please try again."; }
    }

    // Update state
    state.current = output;
    state.feedback = feedback;
    state.history.push({ output, valid, feedback });

    const iterMs = Date.now() - iterStart;
    iterationHistory.push({ iteration: i, valid, duration_ms: iterMs, feedback });

    // Trace
    counter("cognition.loop.iteration", { loop: config.name, iteration: String(i), valid: String(valid) });
    histogram("cognition.loop.iteration_ms", iterMs, { loop: config.name });

    // Short-circuit on success
    if (valid) {
      logger.info("loop.success", { loop: config.name, iterations: i + 1, total_ms: Date.now() - startMs });
      break;
    }
  }

  const totalMs = Date.now() - startMs;

  // Write summary span
  await writeSpan({
    trace_id: config.trace_id,
    kind: "loop",
    name: config.name,
    status: bestValid ? "ok" : "exhausted",
    duration_ms: totalMs,
    metadata: {
      iterations: iterationHistory.length,
      max_iterations: config.max_iterations,
      best_iteration: bestIteration,
      valid: bestValid,
    },
  });

  if (!bestValid) {
    counter("cognition.loop.exhausted", { loop: config.name });
    logger.warn("loop.exhausted", { loop: config.name, iterations: iterationHistory.length, total_ms: totalMs });
  }

  return {
    output: bestOutput as T,
    valid: bestValid,
    iterations: iterationHistory.length,
    best_iteration: bestIteration,
    total_ms: totalMs,
    history: iterationHistory,
  };
}

/**
 * Simple generate-until-valid loop.
 * Calls `generate()` repeatedly until `validate()` passes.
 */
export async function generateUntilValid<T>(
  name: string,
  generate: (attempt: number, previousFeedback: string | null) => Promise<T>,
  validate: (output: T) => Promise<boolean> | boolean,
  options: { max_iterations?: number; trace_id?: string; critique?: (output: T) => Promise<string> } = {}
): Promise<LoopResult<T>> {
  return runLoop({
    name,
    max_iterations: options.max_iterations || 3,
    trace_id: options.trace_id || "loop-" + Date.now(),
    step: (state, i) => generate(i, state.feedback),
    validate,
    critique: options.critique,
  });
}

/**
 * Generate → Critique → Revise loop.
 * First iteration generates from scratch. Subsequent iterations revise based on feedback.
 */
export async function generateCritiqueRevise<T>(
  name: string,
  generate: (spec: string) => Promise<T>,
  critique: (output: T) => Promise<string>,
  revise: (output: T, feedback: string) => Promise<T>,
  validate: (output: T) => Promise<boolean> | boolean,
  spec: string,
  options: { max_iterations?: number; trace_id?: string } = {}
): Promise<LoopResult<T>> {
  return runLoop({
    name,
    max_iterations: options.max_iterations || 3,
    trace_id: options.trace_id || "loop-" + Date.now(),
    step: async (state, i) => {
      if (i === 0 || !state.current) return generate(spec);
      return revise(state.current, state.feedback || "Please improve.");
    },
    validate,
    critique,
  });
}
