"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — typed prompt callers.
//
// One async function per declared `prompt`. Each function:
//   1. validates input via the prompt's Zod schema (reusing src/schemas.ts)
//   2. resolves the model from a static model_ref OR a router
//   3. loads the template body from src/extensions.ts (extension_point)
//   4. dispatches the call through the provider adapter
//   5. validates the response per prompt.validate (none / schema_only /
//      ast_compiles / custom)
//   6. handles on_invalid: fail / retry / retry_with_repair_prompt /
//      escalate within the prompt's retry budget
//   7. emits a span via the cognition_traces logger
//   8. returns the typed result
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROMPTS = void 0;
exports.getPrompt = getPrompt;
exports.findSummarizer = findSummarizer;
const logger_1 = require("../logger");
const metrics_1 = require("../metrics");
const providers_1 = require("../providers");
const budget_1 = require("./budget");
const validate_1 = require("./validate");
const traces_1 = require("./traces");
const repair_1 = require("./repair");
const cache_1 = require("./cache");
const crypto_1 = require("crypto");
const router_1 = require("./router");
// Extension-point templates — bodies live in src/extensions.ts and are
// preserved across recompilation. We refer to them by name to keep the
// compiled file decoupled from prompt wording.
function loadExtension(name) {
    // Late-bind so module load order doesn't matter.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const ext = require("../extensions");
    const fn = ext[name];
    if (typeof fn !== "function") {
        throw new Error(`Extension point not implemented: ${name}. ` +
            `Open src/extensions.ts and fill in the body between the sentinel comments.`);
    }
    return fn;
}
function parseModelOutput(raw, expected) {
    if (expected === "string") {
        // For string outputs (typically code or markdown), strip surrounding
        // markdown fences if present so the consumer gets just the inner
        // content. Most models wrap their output in ```typescript ... ``` or
        // ```ts or just ``` — we handle all three. If multiple fences are
        // present, we pick the largest typescript-tagged one (or the largest
        // untagged fallback). If no fence at all, return raw unchanged.
        return extractLargestFencedBlock(raw);
    }
    if (expected === "unknown") {
        try {
            return JSON.parse(raw);
        }
        catch {
            return raw;
        }
    }
    if (expected === "file" || expected === "files") {
        // Multi-file output. The model should return JSON: a single
        // { path, content, kind? } record for `file`, or an array for
        // `files`. We strip a code fence first since models often wrap
        // structured output in ```json ... ```. If parsing fails entirely,
        // fall back to a single-file synthesis where the whole raw output
        // is the content and `path` is empty — the validator will reject
        // this and trigger repair, so we surface the issue without crashing.
        const cleaned = raw.replace(/^```[a-zA-Z]*\n?/, "").replace(/```\s*$/, "").trim();
        let parsed;
        try {
            parsed = JSON.parse(cleaned);
        }
        catch {
            return expected === "files" ? [{ path: "", content: raw }] : { path: "", content: raw };
        }
        if (expected === "files") {
            // Accept a bare array, OR an object with a top-level `files` field
            // (a common model framing — "here are the files: { files: [...] }").
            if (Array.isArray(parsed))
                return parsed;
            if (parsed && typeof parsed === "object" && Array.isArray(parsed.files)) {
                return parsed.files;
            }
            // Last resort: single-record-into-list promotion.
            if (parsed && typeof parsed === "object" && "path" in parsed)
                return [parsed];
            return [{ path: "", content: String(parsed) }];
        }
        // expected === "file"
        if (Array.isArray(parsed) && parsed.length > 0)
            return parsed[0];
        return parsed;
    }
    // expected === json
    // Strip a markdown code fence if the model wrapped its JSON in ```json ... ```.
    const cleaned = raw.replace(/^```[a-zA-Z]*\n?/, "").replace(/```\s*$/, "").trim();
    return JSON.parse(cleaned);
}
function extractLargestFencedBlock(raw) {
    const fenceRe = /```([a-zA-Z]*)\s*\n([\s\S]*?)\n```/g;
    const tsFences = [];
    const untaggedFences = [];
    let m;
    while ((m = fenceRe.exec(raw)) !== null) {
        const lang = (m[1] || "").toLowerCase();
        const body = m[2];
        if (lang === "typescript" || lang === "ts" || lang === "tsx" || lang === "javascript" || lang === "js") {
            tsFences.push(body);
        }
        else if (lang === "") {
            untaggedFences.push(body);
        }
        else {
            // Other languages (markdown, python, etc.) — keep them in untagged
            // pool as a fallback so the validator at least sees something.
            untaggedFences.push(body);
        }
    }
    const pool = tsFences.length > 0 ? tsFences : untaggedFences;
    if (pool.length === 0)
        return raw;
    let best = pool[0];
    for (let i = 1; i < pool.length; i++) {
        if (pool[i].length > best.length)
            best = pool[i];
    }
    return best;
}
// Prompt: classify_task_type
// model: TinyClassifier
// validate: schema_only | on_invalid: retry | timeout: 3000ms
async function prompt_classify_task_type(input, ctx) {
    const __start = Date.now();
    const __model = (0, providers_1.getModel)("TinyClassifier");
    const __tier = "fixed";
    const __template = loadExtension("tmpl_classify_task");
    const __rendered = String(__template(...Object.values(input)));
    const __messages = [{ role: "user", content: __rendered }];
    const __templateHash = (0, crypto_1.createHash)("sha256").update(__rendered).digest("hex").slice(0, 16);
    const __userKey = (() => {
        try {
            return String((0, crypto_1.createHash)("sha256").update(String(input["user_message"] ?? "")).digest("hex").slice(0, 16));
        }
        catch {
            return "";
        }
    })();
    const __cacheKey = (0, cache_1.deriveKey)({
        prompt_name: "classify_task_type",
        model_id: __model.name,
        template_hash: __templateHash + ":" + __userKey,
        output_type: "string",
        input,
    });
    const __hit = await cache_1.cache.get(__cacheKey);
    if (__hit) {
        logger_1.logger.info("cognition_prompt_cache_hit", {
            event: "classify_task_type",
            status: "success",
            duration_ms: 0,
            trace_id: ctx.trace_id,
            metadata: { model: __model.name, cache_hit: true }
        });
        await (0, traces_1.writeSpan)({
            trace_id: ctx.trace_id,
            workflow: "classify_task_type",
            step: "cache_lookup",
            kind: "cache_hit",
            prompt: "classify_task_type",
            model: __model.name,
            provider: __model.provider.name,
            input,
            output: __hit.value,
            prompt_tokens: __hit.prompt_tokens ?? undefined,
            completion_tokens: __hit.completion_tokens ?? undefined,
            latency_ms: 0,
            cache_hit: true,
            status: "cache_hit",
        });
        return __hit.value;
    }
    const __budget = ctx.budget ?? (0, budget_1.newBudget)(ctx.trace_id);
    const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
    const __maxAttempts = 2;
    let __lastError = null;
    for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
        const __controller = new AbortController();
        const __timer = setTimeout(() => __controller.abort(), 3000);
        if (ctx.signal)
            ctx.signal.addEventListener("abort", () => __controller.abort());
        try {
            (0, metrics_1.counter)("cognition.prompt_calls", { prompt: "classify_task_type", model: __model.name });
            // Budget gate — refuse if this attempt would push the trace over either ceiling.
            __budget.assertCanSpend(__estimatedTokens, __model.costClass);
            const __resp = await __model.provider.chat({
                model: __model.modelName,
                messages: __messages,
                temperature: __model.temperature,
                top_p: __model.topP ?? undefined,
                max_output: __model.maxOutput,
                stop: __model.stop,
                json: false,
            }, __controller.signal);
            clearTimeout(__timer);
            const __value = parseModelOutput(__resp.content, "string");
            const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
            // validate: schema_only — structural check against string
            const __report = (0, validate_1.validateSchemaOnly)(__value, "string");
            if (!__report.ok) {
                const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
                __vErr.__validationIssues = __report.issues;
                __vErr.__badOutput = __value;
                throw __vErr;
            }
            const __elapsed = Date.now() - __start;
            // Phase 3: actual usage — refund the over-estimate, charge the truth.
            const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
            // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
            __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
            // Phase 3: write to cache.
            try {
                await cache_1.cache.put(__cacheKey, "classify_task_type", __model.name, __value, 600000, {
                    prompt_tokens: __resp.usage.prompt_tokens,
                    completion_tokens: __resp.usage.completion_tokens,
                });
            }
            catch (__cacheErr) {
                // Cache write failures are not fatal — log and continue.
                logger_1.logger.warn("prompt_cache_write_failed", { event: "classify_task_type", status: "rejected", trace_id: ctx.trace_id });
            }
            (0, metrics_1.histogram)("cognition.prompt_latency_ms", __elapsed, { prompt: "classify_task_type", model: __model.name });
            logger_1.logger.info("cognition_prompt_ok", {
                event: "classify_task_type",
                status: "success",
                duration_ms: __elapsed,
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
            });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "classify_task_type",
                step: "chat",
                kind: "prompt_call",
                prompt: "classify_task_type",
                model: __model.name,
                provider: __model.provider.name,
                input,
                output: __value,
                validate_result: "ok",
                confidence: __confidence ?? undefined,
                prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                completion_tokens: __resp.usage.completion_tokens ?? undefined,
                latency_ms: __elapsed,
                cache_hit: false,
                status: "ok",
                metadata: { attempt: __attempt, tier: __tier },
            });
            return __value;
        }
        catch (__err) {
            clearTimeout(__timer);
            __lastError = __err;
            // Budget exceptions are terminal — no retry, no escalate, just bubble.
            if (__err instanceof budget_1.BudgetExceededError) {
                logger_1.logger.error("cognition_budget_exceeded", {
                    event: "classify_task_type",
                    status: "rejected",
                    trace_id: ctx.trace_id,
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
                });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "classify_task_type",
                    step: "budget",
                    kind: "budget_exceeded",
                    prompt: "classify_task_type",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    latency_ms: Date.now() - __start,
                    status: "budget_exceeded",
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
                });
                throw __err;
            }
            (0, metrics_1.counter)("cognition.prompt_failed", { prompt: "classify_task_type", model: __model.name });
            const __msg = __err instanceof Error ? __err.message : String(__err);
            logger_1.logger.warn("cognition_prompt_failed", {
                event: "classify_task_type",
                status: "rejected",
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
            });
            {
                const __issues = __err.__validationIssues;
                const __isValidate = Array.isArray(__issues);
                const __isLowConf = typeof __err.__lowConfidence === "number";
                const __badOut = __err.__badOutput;
                if (!__isLowConf) {
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "classify_task_type",
                        step: __isValidate ? "validate" : "chat",
                        kind: __isValidate ? "validate" : "prompt_call",
                        prompt: "classify_task_type",
                        model: __model.name,
                        provider: __model.provider.name,
                        input,
                        output: __isValidate ? __badOut : undefined,
                        validate_result: __isValidate ? "failed" : undefined,
                        latency_ms: Date.now() - __start,
                        status: __isValidate ? "validate_failed" : "provider_error",
                        error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
                        metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
                    });
                }
            }
            // on_invalid: retry — fall through to next attempt
            if (__attempt < __maxAttempts)
                await new Promise(r => setTimeout(r, 100));
        }
    }
    throw __lastError ?? new Error("Prompt classify_task_type failed after retries");
}
// Prompt: code_assist
// model: router:coding_router
// validate: schema_only | on_invalid: retry_with_repair_prompt | timeout: 120000ms
async function prompt_code_assist(input, ctx) {
    const __start = Date.now();
    const __router = (0, router_1.getRouter)("coding_router");
    const __routeChoice = __router.route(input);
    let __model = __routeChoice.model;
    let __tier = __routeChoice.tier;
    const __template = loadExtension("tmpl_code_assist");
    const __rendered = String(__template(...Object.values(input)));
    const __messages = [{ role: "user", content: __rendered }];
    const __budget = ctx.budget ?? (0, budget_1.newBudget)(ctx.trace_id);
    const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
    const __maxAttempts = 3;
    let __lastError = null;
    for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
        const __controller = new AbortController();
        const __timer = setTimeout(() => __controller.abort(), 120000);
        if (ctx.signal)
            ctx.signal.addEventListener("abort", () => __controller.abort());
        try {
            (0, metrics_1.counter)("cognition.prompt_calls", { prompt: "code_assist", model: __model.name });
            // Budget gate — refuse if this attempt would push the trace over either ceiling.
            __budget.assertCanSpend(__estimatedTokens, __model.costClass);
            const __resp = await __model.provider.chat({
                model: __model.modelName,
                messages: __messages,
                temperature: __model.temperature,
                top_p: __model.topP ?? undefined,
                max_output: __model.maxOutput,
                stop: __model.stop,
                json: false,
            }, __controller.signal);
            clearTimeout(__timer);
            const __value = parseModelOutput(__resp.content, "string");
            // Phase 7: low-confidence check (router=coding_router, threshold=0.6, on_low_confidence=escalate)
            const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
            if (__confidence !== null && __confidence < 0.6) {
                (0, metrics_1.counter)("cognition.low_confidence", { prompt: "code_assist", model: __model.name });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "low_confidence",
                    kind: "low_confidence",
                    prompt: "code_assist",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    output: __value,
                    confidence: __confidence,
                    prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                    completion_tokens: __resp.usage.completion_tokens ?? undefined,
                    latency_ms: Date.now() - __start,
                    status: "low_confidence",
                    metadata: { threshold: 0.6, on_low_confidence: "escalate", attempt: __attempt, tier: __tier },
                });
                const __lcErr = new Error("low confidence: " + __confidence.toFixed(3) + " < 0.6");
                __lcErr.__validationIssues = ["confidence " + __confidence.toFixed(3) + " < 0.6"];
                __lcErr.__badOutput = __value;
                __lcErr.__lowConfidence = __confidence;
                throw __lcErr;
            }
            // validate: schema_only — structural check against string
            const __report = (0, validate_1.validateSchemaOnly)(__value, "string");
            if (!__report.ok) {
                const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
                __vErr.__validationIssues = __report.issues;
                __vErr.__badOutput = __value;
                throw __vErr;
            }
            const __elapsed = Date.now() - __start;
            // Phase 3: actual usage — refund the over-estimate, charge the truth.
            const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
            // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
            __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
            (0, metrics_1.histogram)("cognition.prompt_latency_ms", __elapsed, { prompt: "code_assist", model: __model.name });
            logger_1.logger.info("cognition_prompt_ok", {
                event: "code_assist",
                status: "success",
                duration_ms: __elapsed,
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
            });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "code_assist",
                step: "chat",
                kind: "prompt_call",
                prompt: "code_assist",
                model: __model.name,
                provider: __model.provider.name,
                input,
                output: __value,
                validate_result: "ok",
                confidence: __confidence ?? undefined,
                prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                completion_tokens: __resp.usage.completion_tokens ?? undefined,
                latency_ms: __elapsed,
                cache_hit: false,
                status: "ok",
                metadata: { attempt: __attempt, tier: __tier },
            });
            return __value;
        }
        catch (__err) {
            clearTimeout(__timer);
            __lastError = __err;
            // Budget exceptions are terminal — no retry, no escalate, just bubble.
            if (__err instanceof budget_1.BudgetExceededError) {
                logger_1.logger.error("cognition_budget_exceeded", {
                    event: "code_assist",
                    status: "rejected",
                    trace_id: ctx.trace_id,
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
                });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "budget",
                    kind: "budget_exceeded",
                    prompt: "code_assist",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    latency_ms: Date.now() - __start,
                    status: "budget_exceeded",
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
                });
                throw __err;
            }
            (0, metrics_1.counter)("cognition.prompt_failed", { prompt: "code_assist", model: __model.name });
            const __msg = __err instanceof Error ? __err.message : String(__err);
            logger_1.logger.warn("cognition_prompt_failed", {
                event: "code_assist",
                status: "rejected",
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
            });
            {
                const __issues = __err.__validationIssues;
                const __isValidate = Array.isArray(__issues);
                const __isLowConf = typeof __err.__lowConfidence === "number";
                const __badOut = __err.__badOutput;
                if (!__isLowConf) {
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "code_assist",
                        step: __isValidate ? "validate" : "chat",
                        kind: __isValidate ? "validate" : "prompt_call",
                        prompt: "code_assist",
                        model: __model.name,
                        provider: __model.provider.name,
                        input,
                        output: __isValidate ? __badOut : undefined,
                        validate_result: __isValidate ? "failed" : undefined,
                        latency_ms: Date.now() - __start,
                        status: __isValidate ? "validate_failed" : "provider_error",
                        error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
                        metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
                    });
                }
            }
            // on_invalid: retry_with_repair_prompt — single-shot repair via the same model
            {
                const __issues = __err.__validationIssues ?? [];
                if (__issues.length === 0) {
                    // Non-validation error — fall through to a normal retry.
                }
                else {
                    const __repairFn = repair_1.REPAIRS["code_assist"];
                    if (__repairFn) {
                        const __repair = await __repairFn({
                            original_input: input,
                            bad_output: __err && __err.__badOutput,
                            issues: __issues,
                        }, { trace_id: ctx.trace_id, signal: ctx.signal });
                        if (__repair.ok && __repair.value !== null) {
                            try {
                                const __repaired = parseModelOutput(String(__repair.value), "string");
                                // Re-validate the repaired output. We only accept it if it passes.
                                const __reReport = (0, validate_1.validateSchemaOnly)(__repaired, "string");
                                if (__reReport.ok) {
                                    __budget.charge(__repair.tokens_used || 0, __model.costClass);
                                    (0, metrics_1.counter)("cognition.repair.accepted", { prompt: "code_assist" });
                                    logger_1.logger.info("cognition_repair_accepted", { event: "code_assist", status: "success", trace_id: ctx.trace_id });
                                    await (0, traces_1.writeSpan)({
                                        trace_id: ctx.trace_id,
                                        workflow: "code_assist",
                                        step: "repair",
                                        kind: "repair",
                                        prompt: "code_assist",
                                        model: __model.name,
                                        provider: __model.provider.name,
                                        input,
                                        output: __repaired,
                                        validate_result: "ok",
                                        completion_tokens: __repair.tokens_used || undefined,
                                        latency_ms: Date.now() - __start,
                                        status: "repair_accepted",
                                        metadata: { issues_count: __issues.length, attempt: __attempt },
                                    });
                                    return __repaired;
                                }
                                (0, metrics_1.counter)("cognition.repair.rejected", { prompt: "code_assist" });
                                await (0, traces_1.writeSpan)({
                                    trace_id: ctx.trace_id,
                                    workflow: "code_assist",
                                    step: "repair",
                                    kind: "repair",
                                    prompt: "code_assist",
                                    model: __model.name,
                                    provider: __model.provider.name,
                                    input,
                                    output: __repaired,
                                    validate_result: "failed",
                                    completion_tokens: __repair.tokens_used || undefined,
                                    latency_ms: Date.now() - __start,
                                    status: "repair_rejected",
                                    metadata: { issues_count: __issues.length, re_issues: __reReport.issues.slice(0, 5) },
                                });
                            }
                            catch (__parseErr) {
                                (0, metrics_1.counter)("cognition.repair.unparseable", { prompt: "code_assist" });
                            }
                        }
                    }
                }
                // Repair failed (or no repair available) — fall through to next attempt.
            }
            if (__attempt < __maxAttempts)
                await new Promise(r => setTimeout(r, 1000 * Math.pow(2, __attempt - 1)));
        }
    }
    // Last-chance fallback escalation: local model exhausted retries.
    //   1. Find the router's fallback model.
    //   2. If it's distinct from the model that just failed, retry once
    //      with the fallback model + a fresh repair attempt budget.
    //   3. Emit a span tagged escalate / fallback so traces show the swap.
    {
        const __fb = __router.fallback();
        // Only swap if the fallback differs from the model that just failed.
        // Compare by name since the router never exposes a stable id at runtime.
        if (__fb && __fb.model.name !== __model.name) {
            (0, metrics_1.counter)("cognition.fallback.attempted", { prompt: "code_assist", from_model: __model.name, to_model: __fb.model.name });
            logger_1.logger.info("cognition_fallback_attempt", { event: "code_assist", status: "success", trace_id: ctx.trace_id, metadata: { from_model: __model.name, to_model: __fb.model.name, after_attempts: __maxAttempts } });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "code_assist",
                step: "fallback",
                kind: "escalate",
                prompt: "code_assist",
                model: __fb.model.name,
                provider: __fb.model.provider.name,
                latency_ms: Date.now() - __start,
                status: "escalated",
                metadata: { from_tier: __tier, to_tier: "fallback", from_model: __model.name, to_model: __fb.model.name, exhausted_attempts: __maxAttempts },
            });
            // Swap to the fallback model and run one bounded attempt.
            const __fbModel = __fb.model;
            const __fbController = new AbortController();
            const __fbTimer = setTimeout(() => __fbController.abort(), 120000);
            if (ctx.signal)
                ctx.signal.addEventListener("abort", () => __fbController.abort());
            try {
                const __fbEstimatedTokens = __fbModel.provider.countTokens(__rendered) + (__fbModel.maxOutput || 256);
                __budget.assertCanSpend(__fbEstimatedTokens, __fbModel.costClass);
                const __fbResp = await __fbModel.provider.chat({
                    messages: [{ role: "user", content: __rendered }],
                    model: __fbModel.modelName,
                    temperature: __fbModel.temperature,
                    max_output: __fbModel.maxOutput,
                }, __fbController.signal);
                clearTimeout(__fbTimer);
                const __fbValue = parseModelOutput(__fbResp.content, "string");
                const __fbReport = (0, validate_1.validateSchemaOnly)(__fbValue, "string");
                const __fbTokensUsed = (__fbResp.usage?.completion_tokens ?? 0) + (__fbResp.usage?.prompt_tokens ?? 0);
                if (__fbReport.ok) {
                    __budget.charge(__fbTokensUsed || __fbEstimatedTokens, __fbModel.costClass);
                    (0, metrics_1.counter)("cognition.fallback.accepted", { prompt: "code_assist", model: __fbModel.name });
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "code_assist",
                        step: "fallback_call",
                        kind: "prompt_call",
                        prompt: "code_assist",
                        model: __fbModel.name,
                        provider: __fbModel.provider.name,
                        input,
                        output: __fbValue,
                        validate_result: "ok",
                        prompt_tokens: __fbResp.usage?.prompt_tokens,
                        completion_tokens: __fbResp.usage?.completion_tokens,
                        latency_ms: Date.now() - __start,
                        status: "ok",
                        metadata: { fallback: true, from_model: __model.name },
                    });
                    return __fbValue;
                }
                // Fallback also failed validation — record and re-throw the original.
                (0, metrics_1.counter)("cognition.fallback.rejected", { prompt: "code_assist", model: __fbModel.name });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "fallback_call",
                    kind: "validate",
                    prompt: "code_assist",
                    model: __fbModel.name,
                    provider: __fbModel.provider.name,
                    input,
                    output: __fbValue,
                    validate_result: "failed",
                    latency_ms: Date.now() - __start,
                    status: "validate_failed",
                    metadata: { fallback: true, issues: __fbReport.issues.slice(0, 5) },
                });
            }
            catch (__fbErr) {
                clearTimeout(__fbTimer);
                // Fallback model errored. Log + fall through to throw the original.
                const __fbMsg = __fbErr instanceof Error ? __fbErr.message : String(__fbErr);
                logger_1.logger.warn("cognition_fallback_failed", { event: "code_assist", status: "failure", trace_id: ctx.trace_id, metadata: { error: __fbMsg.slice(0, 256) } });
                (0, metrics_1.counter)("cognition.fallback.error", { prompt: "code_assist" });
            }
        }
    }
    throw __lastError ?? new Error("Prompt code_assist failed after retries");
}
// Prompt: compress_history
// model: SmallCoder
// validate: schema_only | on_invalid: retry | timeout: 30000ms
async function prompt_compress_history(input, ctx) {
    const __start = Date.now();
    const __model = (0, providers_1.getModel)("SmallCoder");
    const __tier = "fixed";
    const __template = loadExtension("tmpl_compress_history");
    const __rendered = String(__template(...Object.values(input)));
    const __messages = [{ role: "user", content: __rendered }];
    const __budget = ctx.budget ?? (0, budget_1.newBudget)(ctx.trace_id);
    const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
    const __maxAttempts = 2;
    let __lastError = null;
    for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
        const __controller = new AbortController();
        const __timer = setTimeout(() => __controller.abort(), 30000);
        if (ctx.signal)
            ctx.signal.addEventListener("abort", () => __controller.abort());
        try {
            (0, metrics_1.counter)("cognition.prompt_calls", { prompt: "compress_history", model: __model.name });
            // Budget gate — refuse if this attempt would push the trace over either ceiling.
            __budget.assertCanSpend(__estimatedTokens, __model.costClass);
            const __resp = await __model.provider.chat({
                model: __model.modelName,
                messages: __messages,
                temperature: __model.temperature,
                top_p: __model.topP ?? undefined,
                max_output: __model.maxOutput,
                stop: __model.stop,
                json: false,
            }, __controller.signal);
            clearTimeout(__timer);
            const __value = parseModelOutput(__resp.content, "string");
            const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
            // validate: schema_only — structural check against string
            const __report = (0, validate_1.validateSchemaOnly)(__value, "string");
            if (!__report.ok) {
                const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
                __vErr.__validationIssues = __report.issues;
                __vErr.__badOutput = __value;
                throw __vErr;
            }
            const __elapsed = Date.now() - __start;
            // Phase 3: actual usage — refund the over-estimate, charge the truth.
            const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
            // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
            __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
            (0, metrics_1.histogram)("cognition.prompt_latency_ms", __elapsed, { prompt: "compress_history", model: __model.name });
            logger_1.logger.info("cognition_prompt_ok", {
                event: "compress_history",
                status: "success",
                duration_ms: __elapsed,
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
            });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "compress_history",
                step: "chat",
                kind: "prompt_call",
                prompt: "compress_history",
                model: __model.name,
                provider: __model.provider.name,
                input,
                output: __value,
                validate_result: "ok",
                confidence: __confidence ?? undefined,
                prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                completion_tokens: __resp.usage.completion_tokens ?? undefined,
                latency_ms: __elapsed,
                cache_hit: false,
                status: "ok",
                metadata: { attempt: __attempt, tier: __tier },
            });
            return __value;
        }
        catch (__err) {
            clearTimeout(__timer);
            __lastError = __err;
            // Budget exceptions are terminal — no retry, no escalate, just bubble.
            if (__err instanceof budget_1.BudgetExceededError) {
                logger_1.logger.error("cognition_budget_exceeded", {
                    event: "compress_history",
                    status: "rejected",
                    trace_id: ctx.trace_id,
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
                });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "compress_history",
                    step: "budget",
                    kind: "budget_exceeded",
                    prompt: "compress_history",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    latency_ms: Date.now() - __start,
                    status: "budget_exceeded",
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
                });
                throw __err;
            }
            (0, metrics_1.counter)("cognition.prompt_failed", { prompt: "compress_history", model: __model.name });
            const __msg = __err instanceof Error ? __err.message : String(__err);
            logger_1.logger.warn("cognition_prompt_failed", {
                event: "compress_history",
                status: "rejected",
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
            });
            {
                const __issues = __err.__validationIssues;
                const __isValidate = Array.isArray(__issues);
                const __isLowConf = typeof __err.__lowConfidence === "number";
                const __badOut = __err.__badOutput;
                if (!__isLowConf) {
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "compress_history",
                        step: __isValidate ? "validate" : "chat",
                        kind: __isValidate ? "validate" : "prompt_call",
                        prompt: "compress_history",
                        model: __model.name,
                        provider: __model.provider.name,
                        input,
                        output: __isValidate ? __badOut : undefined,
                        validate_result: __isValidate ? "failed" : undefined,
                        latency_ms: Date.now() - __start,
                        status: __isValidate ? "validate_failed" : "provider_error",
                        error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
                        metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
                    });
                }
            }
            // on_invalid: retry — fall through to next attempt
            if (__attempt < __maxAttempts)
                await new Promise(r => setTimeout(r, 500));
        }
    }
    throw __lastError ?? new Error("Prompt compress_history failed after retries");
}
exports.PROMPTS = {
    "classify_task_type": prompt_classify_task_type,
    "code_assist": prompt_code_assist,
    "compress_history": prompt_compress_history,
};
function getPrompt(name) {
    const fn = exports.PROMPTS[name];
    if (!fn)
        throw new Error(`Unknown prompt: ${name}`);
    return fn;
}
/**
 * Find the first prompt that looks like a summariser by convention:
 * any prompt whose name contains "summar". Used by the
 * compress_context cognition primitive when the user has not specified
 * an explicit summariser.
 */
function findSummarizer() {
    for (const name of Object.keys(exports.PROMPTS).sort()) {
        if (/summar/i.test(name))
            return exports.PROMPTS[name];
    }
    return null;
}
