"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — deterministic routing decision trees.
//
// Each router is a closed list of tiers, evaluated in declaration order
// against the routing key. The last tier is the default. There is no
// dynamic dispatch — the same input always selects the same tier.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROUTERS = void 0;
exports.getRouter = getRouter;
const providers_1 = require("../providers");
/** Pull a numeric value off `input` using a dotted path. Returns NaN on miss. */
function pickByPath(input, path) {
    let cur = input;
    for (const k of path) {
        if (cur === null || cur === undefined)
            return NaN;
        cur = cur[k];
    }
    if (typeof cur === "number")
        return cur;
    if (typeof cur === "string")
        return Number(cur);
    if (Array.isArray(cur))
        return cur.length;
    if (cur && typeof cur === "object")
        return Object.keys(cur).length;
    return NaN;
}
// Router: coding_router
// by: input.complexity
const ROUTER_coding_router = {
    name: "coding_router",
    route(input) {
        const value = pickByPath(input, ["complexity"]);
        if (!Number.isNaN(value) && value <= 0.3) {
            const m = (0, providers_1.getModel)("TinyClassifier");
            return { model_id: "TinyClassifier", tier: "trivial", model: m };
        }
        if (!Number.isNaN(value) && value <= 0.6) {
            const m = (0, providers_1.getModel)("SmallCoder");
            return { model_id: "SmallCoder", tier: "simple", model: m };
        }
        {
            const m = (0, providers_1.getModel)("MediumCoder");
            return { model_id: "MediumCoder", tier: "complex", model: m };
        }
    },
    escalate(currentTier) {
        const order = [
            { name: "trivial", modelRef: "TinyClassifier" },
            { name: "simple", modelRef: "SmallCoder" },
            { name: "complex", modelRef: "MediumCoder" },
        ];
        const idx = order.findIndex(t => t.name === currentTier);
        if (idx < 0 || idx >= order.length - 1)
            return null;
        const next = order[idx + 1];
        return { model_id: next.modelRef, tier: next.name, model: (0, providers_1.getModel)(next.modelRef) };
    },
    fallback() {
        return { model_id: "MediumCoder", tier: "fallback", model: (0, providers_1.getModel)("MediumCoder") };
    },
};
exports.ROUTERS = {
    "coding_router": ROUTER_coding_router,
};
function getRouter(name) {
    const r = exports.ROUTERS[name];
    if (!r)
        throw new Error(`Unknown router: ${name}`);
    return r;
}
