// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — deterministic routing decision trees.
//
// Each router is a closed list of tiers, evaluated in declaration order
// against the routing key. The last tier is the default. There is no
// dynamic dispatch — the same input always selects the same tier.

import { getModel, type ModelEntry } from "../providers";

export interface RouteChoice {
  /** Declared model name. */
  model_id: string;
  /** The tier whose threshold matched. */
  tier: string;
  /** Resolved model entry — convenience for prompt callers. */
  model: ModelEntry;
}

export interface CompiledRouter {
  name: string;
  /** Pick a tier given the routing input. */
  route(input: unknown): RouteChoice;
  /** Move up one tier. Returns null if currentTier is the top. */
  escalate(currentTier: string): RouteChoice | null;
  /** Optional fallback model when on_low_confidence: escalate exhausts tiers. */
  fallback(): RouteChoice | null;
}

/** Pull a numeric value off `input` using a dotted path. Returns NaN on miss. */
function pickByPath(input: unknown, path: string[]): number {
  let cur: any = input;
  for (const k of path) {
    if (cur === null || cur === undefined) return NaN;
    cur = cur[k];
  }
  if (typeof cur === "number") return cur;
  if (typeof cur === "string") return Number(cur);
  if (Array.isArray(cur)) return cur.length;
  if (cur && typeof cur === "object") return Object.keys(cur).length;
  return NaN;
}

// Router: coding_router
// by: input.complexity
const ROUTER_coding_router: CompiledRouter = {
  name: "coding_router",
  route(input: unknown): RouteChoice {
    const value = pickByPath(input, ["complexity"]);
    if (!Number.isNaN(value) && value <= 0.3) {
      const m = getModel("TinyClassifier");
      return { model_id: "TinyClassifier", tier: "trivial", model: m };
    }
    if (!Number.isNaN(value) && value <= 0.6) {
      const m = getModel("SmallCoder");
      return { model_id: "SmallCoder", tier: "simple", model: m };
    }
    {
      const m = getModel("MediumCoder");
      return { model_id: "MediumCoder", tier: "complex", model: m };
    }
  },
  escalate(currentTier: string): RouteChoice | null {
    const order: { name: string; modelRef: string }[] = [
      { name: "trivial", modelRef: "TinyClassifier" },
      { name: "simple", modelRef: "SmallCoder" },
      { name: "complex", modelRef: "MediumCoder" },
    ];
    const idx = order.findIndex(t => t.name === currentTier);
    if (idx < 0 || idx >= order.length - 1) return null;
    const next = order[idx + 1];
    return { model_id: next.modelRef, tier: next.name, model: getModel(next.modelRef) };
  },
  fallback(): RouteChoice | null {
    return { model_id: "MediumCoder", tier: "fallback", model: getModel("MediumCoder") };
  },
};

export const ROUTERS: Record<string, CompiledRouter> = {
  "coding_router": ROUTER_coding_router,
};

export function getRouter(name: string): CompiledRouter {
  const r = ROUTERS[name];
  if (!r) throw new Error(`Unknown router: ${name}`);
  return r;
}
