"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 6 — span writer.
//
// Every prompt invocation emits one or more spans through writeSpan().
// Spans never block the caller: persistence failures are logged and
// swallowed so a broken DB can't take down inference.
//
// Three backends, switched by LLM_TRACES_BACKEND env var:
//   memory (default)  — in-process ring buffer, capped at 10k spans
//   pg                — Postgres-backed via src/db pool
//   none              — drop everything (silent)
//
// Redaction mirrors src/audit.ts: any key in ALWAYS_REDACT (case-insensitive)
// or a @sensitive-tagged field is replaced with "[REDACTED]".
Object.defineProperty(exports, "__esModule", { value: true });
exports.redactForTrace = redactForTrace;
exports.writeSpan = writeSpan;
exports.loadTrace = loadTrace;
exports.__resetTraces = __resetTraces;
const crypto_1 = require("crypto");
const logger_1 = require("../logger");
const metrics_1 = require("../metrics");
// Per-entity @sensitive field map, derived at compile time.
const SENSITIVE_FIELDS = {};
// Always-redacted keys regardless of entity. Names matched case-insensitively.
const ALWAYS_REDACT = new Set([
    "password", "passwd", "pwd", "secret", "token", "api_key", "apikey",
    "authorization", "bearer", "ssn", "card_number", "cvv",
]);
function redactValue(value, entityHint) {
    if (value === null || value === undefined)
        return value;
    if (typeof value !== "object")
        return value;
    if (Array.isArray(value))
        return value.map(v => redactValue(v, entityHint));
    const out = {};
    const sensitiveSet = entityHint ? new Set(SENSITIVE_FIELDS[entityHint] || []) : new Set();
    for (const [k, v] of Object.entries(value)) {
        if (ALWAYS_REDACT.has(k.toLowerCase()) || sensitiveSet.has(k)) {
            out[k] = "[REDACTED]";
        }
        else {
            out[k] = redactValue(v, entityHint);
        }
    }
    return out;
}
function redactForTrace(value, entityHint) {
    return redactValue(value, entityHint);
}
class MemoryBackend {
    buffer = [];
    cap = 10_000;
    async write(span) {
        this.buffer.push(span);
        if (this.buffer.length > this.cap) {
            this.buffer.splice(0, this.buffer.length - this.cap);
        }
    }
    async loadTrace(trace_id) {
        return this.buffer.filter(s => s.trace_id === trace_id).sort((a, b) => a.started_at - b.started_at);
    }
    __reset() { this.buffer = []; }
}
class PgBackend {
    async write(span) {
        // Lazy import — keeps tests that don't exercise PG free of pg.
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const { query } = require("../db");
        await query(`INSERT INTO cognition_traces (
        span_id, trace_id, parent_span_id, workflow, step, kind, prompt, model, provider,
        input_redacted, output_redacted, validate_result, confidence,
        prompt_tokens, completion_tokens, cost_usd, latency_ms, cache_hit,
        status, error_code, metadata, started_at, finished_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15, $16, $17, $18,
        $19, $20, $21, to_timestamp($22 / 1000.0), to_timestamp($23 / 1000.0)
      )
      ON CONFLICT (span_id) DO NOTHING`, [
            span.span_id, span.trace_id, span.parent_span_id,
            span.workflow, span.step, span.kind, span.prompt, span.model, span.provider,
            JSON.stringify(span.input_redacted), JSON.stringify(span.output_redacted),
            span.validate_result, span.confidence,
            span.prompt_tokens, span.completion_tokens, span.cost_usd, span.latency_ms, span.cache_hit,
            span.status, span.error_code, JSON.stringify(span.metadata),
            span.started_at, span.finished_at,
        ]);
    }
    async loadTrace(trace_id) {
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const { query } = require("../db");
        const rows = await query("SELECT * FROM cognition_traces WHERE trace_id = $1 ORDER BY started_at", [trace_id]);
        return rows.map(rowToSpan);
    }
}
class NoopBackend {
    async write(_span) { }
    async loadTrace(_trace_id) { return []; }
}
function rowToSpan(r) {
    return {
        span_id: String(r.span_id),
        trace_id: String(r.trace_id),
        parent_span_id: r.parent_span_id == null ? null : String(r.parent_span_id),
        workflow: String(r.workflow),
        step: String(r.step),
        kind: r.kind,
        prompt: r.prompt == null ? null : String(r.prompt),
        model: r.model == null ? null : String(r.model),
        provider: r.provider == null ? null : String(r.provider),
        input_redacted: r.input_redacted ?? null,
        output_redacted: r.output_redacted ?? null,
        validate_result: r.validate_result == null ? null : String(r.validate_result),
        confidence: r.confidence == null ? null : Number(r.confidence),
        prompt_tokens: r.prompt_tokens == null ? null : Number(r.prompt_tokens),
        completion_tokens: r.completion_tokens == null ? null : Number(r.completion_tokens),
        cost_usd: r.cost_usd == null ? null : Number(r.cost_usd),
        latency_ms: Number(r.latency_ms ?? 0),
        cache_hit: Boolean(r.cache_hit),
        status: r.status,
        error_code: r.error_code == null ? null : String(r.error_code),
        metadata: r.metadata ?? {},
        started_at: r.started_at instanceof Date ? r.started_at.getTime() : Number(r.started_at),
        finished_at: r.finished_at == null ? null : (r.finished_at instanceof Date ? r.finished_at.getTime() : Number(r.finished_at)),
    };
}
function chooseBackend() {
    const mode = process.env.LLM_TRACES_BACKEND || "memory";
    if (mode === "pg")
        return new PgBackend();
    if (mode === "none")
        return new NoopBackend();
    if (mode !== "memory") {
        logger_1.logger.warn("traces_unknown_backend", { event: "traces", status: "rejected", metadata: { mode } });
    }
    return new MemoryBackend();
}
const __backend = chooseBackend();
/**
 * Persist a cognition span. Never throws — failures are logged and counted.
 * The span_id is generated here so callers don't have to reach for randomUUID.
 */
async function writeSpan(init) {
    const now = Date.now();
    const span = {
        span_id: (0, crypto_1.randomUUID)(),
        trace_id: init.trace_id,
        parent_span_id: init.parent_span_id ?? null,
        workflow: init.workflow,
        step: init.step,
        kind: init.kind,
        prompt: init.prompt ?? null,
        model: init.model ?? null,
        provider: init.provider ?? null,
        input_redacted: init.input === undefined ? null : redactValue(init.input, init.input_entity_hint),
        output_redacted: init.output === undefined ? null : redactValue(init.output, init.output_entity_hint),
        validate_result: init.validate_result ?? null,
        confidence: init.confidence ?? null,
        prompt_tokens: init.prompt_tokens ?? null,
        completion_tokens: init.completion_tokens ?? null,
        cost_usd: init.cost_usd ?? null,
        latency_ms: init.latency_ms,
        cache_hit: init.cache_hit ?? false,
        status: init.status,
        error_code: init.error_code ?? null,
        metadata: init.metadata ?? {},
        started_at: now - init.latency_ms,
        finished_at: now,
    };
    try {
        await __backend.write(span);
        (0, metrics_1.counter)("cognition.span_written", { kind: init.kind, status: init.status });
    }
    catch (e) {
        (0, metrics_1.counter)("cognition.span_write_failed");
        const msg = e instanceof Error ? e.message : String(e);
        logger_1.logger.warn("cognition_span_write_failed", { event: "traces", status: "rejected", trace_id: span.trace_id, metadata: { error: msg.slice(0, 256) } });
    }
    return span.span_id;
}
/** Load all spans for a trace, sorted by start time. */
async function loadTrace(trace_id) {
    return __backend.loadTrace(trace_id);
}
/** For tests: reset the in-memory backend. */
function __resetTraces() {
    if (__backend.__reset)
        __backend.__reset();
}
