"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Endpoint allowlist for openai_compat / http providers.
//
// Default policy: only loopback (127.0.0.0/8, ::1, localhost) and RFC1918
// (10/8, 172.16/12, 192.168/16) are allowed without an explicit env override.
// Set LLM_ENDPOINT_ALLOWLIST=https://api.example.com,http://internal:8080
// to permit additional endpoints. Setting LLM_ALLOW_PUBLIC_ENDPOINTS=1
// disables the host filter entirely (production-only opt-in).
//
// SECURITY NOTES:
//   - We compare ORIGIN (scheme + host + port), not raw startsWith on the
//     URL string. Otherwise an attacker can register
//     `https://api.evil.com.attacker.com/` against an allowlist of
//     `https://api.evil.com` and bypass the check.
//   - We refuse link-local (169.254/16), CGNAT (100.64/10), and metadata
//     services (169.254.169.254) even when LLM_ALLOW_PUBLIC_ENDPOINTS=1
//     is set, unless the URL was an explicit allowlist match. This blocks
//     classic SSRF-to-cloud-metadata attacks.
Object.defineProperty(exports, "__esModule", { value: true });
exports.assertEndpointAllowed = assertEndpointAllowed;

function isLoopback(host) {
    const h = host.toLowerCase();
    if (h === "localhost" || h === "::1" || h === "::") return true;
    if (h.startsWith("127.")) return true;
    return false;
}

function isRfc1918(host) {
    const m = host.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
    if (!m) return false;
    const a = Number(m[1]), b = Number(m[2]);
    if (a === 10) return true;
    if (a === 172 && b >= 16 && b <= 31) return true;
    if (a === 192 && b === 168) return true;
    return false;
}

// Cloud metadata + link-local + CGNAT — never allowed implicitly.
function isAlwaysBlocked(host) {
    const h = host.toLowerCase();
    if (h === "169.254.169.254") return true; // AWS/GCP/Azure metadata IPv4
    if (h === "fd00:ec2::254" || h === "[fd00:ec2::254]") return true; // AWS IPv6 metadata
    if (h === "metadata.google.internal") return true;
    if (h === "metadata") return true;
    const m = h.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
    if (m) {
        const a = Number(m[1]), b = Number(m[2]);
        if (a === 169 && b === 254) return true; // 169.254/16 link-local
        if (a === 100 && b >= 64 && b <= 127) return true; // 100.64/10 CGNAT
        if (a === 0) return true; // 0.0.0.0/8 reserved
    }
    return false;
}

function originOf(url) {
    // URL.origin returns "scheme://host[:port]" — exactly what we want
    // for prefix matching without falling for path-suffix tricks.
    return url.origin.replace(/\/+$/, "");
}

function originMatches(allowEntry, url) {
    let allowUrl;
    try { allowUrl = new URL(allowEntry); } catch { return false; }
    return originOf(allowUrl) === originOf(url);
}

function assertEndpointAllowed(endpoint) {
    let url;
    try {
        url = new URL(endpoint);
    } catch {
        throw new Error(`Invalid endpoint URL: ${endpoint}`);
    }
    if (url.protocol !== "http:" && url.protocol !== "https:") {
        throw new Error(`Endpoint must use http(s): ${endpoint}`);
    }
    // Always block cloud metadata + link-local + CGNAT, even when the
    // operator explicitly opted into public endpoints. These are never
    // intentionally targeted by an LLM provider.
    if (isAlwaysBlocked(url.hostname)) {
        throw new Error(`Endpoint ${endpoint} targets a metadata/link-local address; refusing.`);
    }
    if (process.env.LLM_ALLOW_PUBLIC_ENDPOINTS === "1") return;

    const allow = (process.env.LLM_ENDPOINT_ALLOWLIST || "").split(",").map(s => s.trim()).filter(Boolean);
    for (const a of allow) {
        if (originMatches(a, url)) return;
    }
    if (isLoopback(url.hostname) || isRfc1918(url.hostname)) return;
    throw new Error(`Endpoint ${endpoint} is not in LLM_ENDPOINT_ALLOWLIST and is not a private host. ` +
        `Set LLM_ENDPOINT_ALLOWLIST=<comma-separated origins> or LLM_ALLOW_PUBLIC_ENDPOINTS=1 to permit.`);
}
