"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — provider interface.
//
// All provider adapters implement IModelProvider. The cognition runtime
// (src/cognition/prompts.ts) talks to this interface only — never to a
// concrete provider — so swapping local Ollama for vLLM is a config change.
Object.defineProperty(exports, "__esModule", { value: true });
exports.approxTokens = approxTokens;
/**
 * Conservative tokenizer. 4 chars/token is the rule of thumb for English
 * across Llama / Qwen / Phi / Gemma families. Off by ~20% in either
 * direction; that's fine for budget gauges, never for billing.
 */
function approxTokens(text) {
    if (!text)
        return 0;
    return Math.ceil(text.length / 4);
}
