"use strict";
// Generated by MarrowScript compiler.
// Extension points: implement the functions below.
// Code between sentinel comments is preserved on recompile.
// DO NOT remove the sentinel comments.
Object.defineProperty(exports, "__esModule", { value: true });
exports.tmpl_classify_task = tmpl_classify_task;
exports.tmpl_compress_history = tmpl_compress_history;
exports.tmpl_code_assist = tmpl_code_assist;
/**
 * Extension point: tmpl_classify_task
 * STABLE: implementation required.
 *
 * Returns a prompt that asks the model to classify the user's task.
 */
function tmpl_classify_task(user_message) {
    // <marrowscript:ext:tmpl_classify_task:begin>
    return `Classify this user message into ONE of these categories. Reply with ONLY the category name, nothing else.

Categories:
- coding: creating new code/files
- editing: modifying existing files
- search: finding files or symbols
- shell: running commands
- explanation: answering questions, explaining concepts
- multi_step: tasks with multiple sequential parts
- debugging: fixing errors or bugs
- backend: building Node.js/TypeScript backends (use BoneScript)

User message: "${user_message}"

Category:`;
    // <marrowscript:ext:tmpl_classify_task:end>
}
/**
 * Extension point: tmpl_compress_history
 * STABLE: implementation required.
 *
 * Returns a prompt that asks the model to compress conversation history.
 */
function tmpl_compress_history(history, max_tokens) {
    // <marrowscript:ext:tmpl_compress_history:begin>
    return `Summarize this conversation history into a concise summary of facts, decisions, and current state. Maximum ${max_tokens} tokens. Keep file paths, error messages, and code identifiers exact.

History:
${history}

Concise summary:`;
    // <marrowscript:ext:tmpl_compress_history:end>
}
/**
 * Extension point: tmpl_code_assist
 * STABLE: implementation required.
 *
 * Returns a prompt for the main code assistance loop with router-selected model.
 */
function tmpl_code_assist(task, context, complexity) {
    // <marrowscript:ext:tmpl_code_assist:begin>
    return `You are SmallCode, a coding agent. Use tools to read, write, edit files and run commands. Be concise.

${context ? 'Context:\n' + context + '\n\n' : ''}Task: ${task}`;
    // <marrowscript:ext:tmpl_code_assist:end>
}
