"use strict";
// @ts-nocheck
// Generated by MarrowScript compiler. DO NOT EDIT.
// Saga runtime â€” implements flow declarations with backward compensation.
//
// On step failure, executes compensations for ALL completed steps in reverse order.
Object.defineProperty(exports, "__esModule", { value: true });
exports.executeFlow = executeFlow;
exports.execute_improvement_loop = execute_improvement_loop;
const logger_1 = require("./logger");
const metrics_1 = require("./metrics");
async function executeFlow(name, steps, ctx) {
    const completed = [];
    for (const step of steps) {
        try {
            logger_1.logger.info("flow_step_started", { event: name + "." + step.name });
            await step.action(ctx);
            completed.push({ step: step.name, compensation: step.compensation });
            (0, metrics_1.counter)("flow.step_completed", { flow: name, step: step.name });
        }
        catch (e) {
            logger_1.logger.error("flow_step_failed", { event: name + "." + step.name, metadata: { error: e.message } });
            (0, metrics_1.counter)("flow.step_failed", { flow: name, step: step.name });
            // Backward compensation in reverse order
            const compensated = [];
            for (const c of [...completed].reverse()) {
                if (!c.compensation)
                    continue;
                try {
                    await c.compensation(ctx);
                    compensated.push(c.step);
                    logger_1.logger.info("flow_compensated", { event: name + "." + c.step });
                }
                catch (compErr) {
                    logger_1.logger.error("flow_compensation_failed", { event: name + "." + c.step, metadata: { error: compErr.message } });
                    // Continue with other compensations even if one fails
                }
            }
            return { ok: false, failed_step: step.name, compensated, error: e.message };
        }
    }
    (0, metrics_1.counter)("flow.completed", { flow: name });
    return { ok: true, compensated: [] };
}
// Flow: improvement_loop
// ctx must contain: { req, res, auth, client? } for transactional flows
async function execute_improvement_loop(ctx) {
    const steps = [
        {
            name: "validate",
            action: async (ctx) => {
                // Calls capability: validate_file(ctx.file_path)
                const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/validate-file`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
                    body: JSON.stringify(ctx.req.body),
                });
                if (!response.ok)
                    throw new Error(`Step validate failed: ${await response.text()}`);
                ctx.validate_result = await response.json();
            },
            compensation: async (ctx) => {
                // Compensates: rollback_file(ctx.file_path)
                await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/rollback-file`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
                    body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
                });
            },
        },
        {
            name: "fix",
            action: async (ctx) => {
                // Calls capability: fix_code(ctx.file_path, validate.output)
                const response = await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/fix-code`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
                    body: JSON.stringify(ctx.req.body),
                });
                if (!response.ok)
                    throw new Error(`Step fix failed: ${await response.text()}`);
                ctx.fix_result = await response.json();
            },
            compensation: async (ctx) => {
                // Compensates: rollback_file(ctx.file_path)
                await fetch(`${process.env.SERVICE_BASE_URL || "http://localhost:3000"}/rollback-file`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json", "Authorization": ctx.req.headers.authorization || "" },
                    body: JSON.stringify({ ...ctx.req.body, _compensating: true }),
                });
            },
        },
    ];
    return executeFlow("improvement_loop", steps, ctx);
}
