"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Implements spec/10 Â§3 (Logging Schema)
Object.defineProperty(exports, "__esModule", { value: true });
exports.logger = void 0;
exports.createLogger = createLogger;
const crypto_1 = require("crypto");
class Logger {
    service;
    constructor(service) {
        this.service = service;
    }
    emit(entry) {
        // SmallCode: only emit logs when explicitly enabled. Otherwise stays silent
        // to avoid polluting CLI output. Set SMALLCODE_COGNITION_LOG=stdout to enable
        // structured logs to stdout, or SMALLCODE_COGNITION_LOG=stderr for stderr.
        const target = process.env.SMALLCODE_COGNITION_LOG;
        if (!target)
            return;
        const full = {
            timestamp: new Date().toISOString(),
            service: this.service,
            span_id: (0, crypto_1.randomUUID)(),
            ...entry,
        };
        const fn = target === "stderr" ? console.error :
            (entry.level === "error" || entry.level === "fatal" ? console.error : console.log);
        fn(JSON.stringify(full));
    }
    info(event, fields = {}) {
        this.emit({ level: "info", event, status: "success", trace_id: fields.trace_id || "", ...fields });
    }
    warn(event, fields = {}) {
        this.emit({ level: "warn", event, status: "rejected", trace_id: fields.trace_id || "", ...fields });
    }
    error(event, fields = {}) {
        this.emit({ level: "error", event, status: "failure", trace_id: fields.trace_id || "", ...fields });
    }
    debug(event, fields = {}) {
        if (process.env.LOG_LEVEL === "debug") {
            this.emit({ level: "debug", event, status: "success", trace_id: fields.trace_id || "", ...fields });
        }
    }
}
function createLogger(service) {
    return new Logger(service);
}
exports.logger = createLogger("SmallCodeCognition");
