"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Implements spec/10 Â§4 (Telemetry Hooks)
Object.defineProperty(exports, "__esModule", { value: true });
exports.counter = counter;
exports.histogram = histogram;
exports.gauge = gauge;
exports.dump = dump;
exports.reset = reset;
const metrics = new Map();
function key(name, labels) {
    const parts = Object.keys(labels).sort().map(k => `${k}="${labels[k]}"`);
    return parts.length > 0 ? `${name}{${parts.join(",")}}` : name;
}
function counter(name, labels = {}) {
    const k = key(name, labels);
    const existing = metrics.get(k);
    if (existing && existing.type === "counter") {
        existing.value++;
    }
    else {
        metrics.set(k, { type: "counter", value: 1, labels });
    }
}
function histogram(name, value, labels = {}) {
    const k = key(name, labels);
    const existing = metrics.get(k);
    if (existing && existing.type === "histogram") {
        existing.values.push(value);
    }
    else {
        metrics.set(k, { type: "histogram", values: [value], labels });
    }
}
function gauge(name, value, labels = {}) {
    const k = key(name, labels);
    metrics.set(k, { type: "gauge", value, labels });
}
function dump() {
    const lines = [];
    for (const [k, m] of metrics.entries()) {
        if (m.type === "counter" || m.type === "gauge") {
            lines.push(`${k} ${m.value}`);
        }
        else {
            const sum = m.values.reduce((a, b) => a + b, 0);
            const count = m.values.length;
            const avg = count > 0 ? sum / count : 0;
            lines.push(`${k}_count ${count}`);
            lines.push(`${k}_sum ${sum}`);
            lines.push(`${k}_avg ${avg.toFixed(2)}`);
        }
    }
    return lines.join("\n");
}
function reset() {
    metrics.clear();
}
